baseURL = 'https://caubechankiu.github.io/'
languageCode = 'vi-VN'
title = "caubechankiu's miscellaneous notes"
theme = 'archie'
copyright = '© caubechankiu'

[params]
  mode="toggle" # color-mode → light,dark,toggle or auto
  useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
  customcss = ["css/archie.css"]
  mathjax = false
  katex = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/caubechankiu"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/trinhthevils"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Search"
url = "/search/"
weight = 4